### ISSUE TITLE
roblox crashes apon startup

### ISSUE THREAD

**Issue by awesomec26** [msmalik681/Maliks-Linux-Roblox-Wrapper#10]
an hour ago, roblox was working fine, then roblox updates and crashes
![Screenshot from 2022-02-12 20-45-33](https://user-images.githubusercontent.com/49694491/153734762-0dc0931b-8922-45f8-8c6b-8d4c11aa962c.png)

**Comment by msmalik681** [comment]
works fine for me try uninstalling and reinstalling there is a update due soon that might work better for you.

**Comment by awesomec26** [comment]
> works fine for me try uninstalling and reinstalling there is a update due soon that might work better for you.

ok, how do i uninstall it

**Comment by msmalik681** [comment]
@awesomec26 please test [version 5.0](https://github.com/msmalik681/Maliks-Linux-Roblox-Wrapper/releases/tag/v5.0) and confirm your have fully updated your system. What distro are you using ?
