### ISSUE TITLE
Roblox does not launch at all.

### ISSUE THREAD

**Issue by morschu** [msmalik681/Maliks-Linux-Roblox-Wrapper#11]
I have tried tried reinstalling my OS too but still roblox wont launch.
My specs are the following
1. GTX 1650
2. RYZEN 5 4600H
3. 8GB RAM
4. 1920X1080
5. Pop_Os!

**Comment by msmalik681** [comment]
Should definitely work on your system join the discord server so i can troubleshoot with you
