### ISSUE TITLE
Roblox freezes when pressing alt + tab or fullscreen

### ISSUE THREAD

**Issue by CloudyyUw** [msmalik681/Maliks-Linux-Roblox-Wrapper#12]
This is a problem I noticed that happened to me a few times in gnome, whenever I pressed alt + tab or super the game crashed.
Apparently it is only a problem with gnome because I re-installed xfce4 to test the problem and it worked fine. I have not tested kde yet to see if this problem occurs there too.
So if you are having this problem too, maybe it is a problem with gnome.
I also saw that in issue #7, when you put it in fullscreen the game freezes. This is a problem that I only had in gnome as well.

This was just to inform some things that I tested. Maybe it will help someone else solve the same or a similar problem.

**Comment by CloudyyUw** [comment]
I also used the latest release in both desktop environments.

**Comment by CloudyyUw** [comment]
Taking a look after a long time, it seems to be a problem with Vulkan, because with OpenGL this has not occurred again.

**Comment by msmalik681** [comment]
Simple solution would to use opengl it is reported to give better fps for most users.
