### ISSUE TITLE
Install script opens pacman (game) on ubuntu

### ISSUE THREAD

**Issue by Alqueno** [msmalik681/Maliks-Linux-Roblox-Wrapper#13]
Hi!
I have to "patch" your installer because on my system, Ubuntu 20.04, "which pacman" returns true, since I have installed the game pacman. Since Arch detection is performed after Ubuntu, the package manager is set erroneously to "pacman". I commented the arch package manager detection and everything worked like a charm. I suggest that either, move ubuntu detection after Arch,  or stop detecting package managers after having found a suitable one.
Thank you a lot for your script. It saved me a lot of time.

Regards

Andrés

**Comment by msmalik681** [comment]
I will fix that in the next update thanks.

**Comment by msmalik681** [comment]
I have moved arch to the bottom of the check list now other distro's with pacman installed will still work.
