### ISSUE TITLE
XDG-OPEN ruin

### ISSUE THREAD

**Issue by Denisbg2011game** [msmalik681/Maliks-Linux-Roblox-Wrapper#14]
os specifications
device: a rpi 4 8gb ram
storage 128gb sd
os: raspbian buster 32bit arm
wine is emulated with box86

when i try to join a game it says xdg-open, when i click it, IT JUST OPENS ANOTHER CHROMIUM WINDOW hows that making sence for a game url, i might try to modify the script to download a arm32 bit version of wine but im not sure if i will be sucsesscufl
anyways @msmalik681 pls help if u can, some more info on the discorddd

**Comment by msmalik681** [comment]
This script was not made for arm devices

**Comment by sylviiu** [comment]
^^

Plus, Roblox's builds that the wrapper uses (win32) are native to the win32 platform -- if you were to try to run Roblox on a pi, the most luck you'd have is using their Android app with something like Waydroid (which I _believe_ runs on arm devices?)

**Comment by msmalik681** [comment]
I will update the readme to confirm the pi is not supported closing this down for now.
