### ISSUE TITLE
Sudden Poor Performance after running fine.

### ISSUE THREAD

**Issue by VeteranSquared** [msmalik681/Maliks-Linux-Roblox-Wrapper#15]
Your wrapper ran at 120 FPS a few days ago. 2 days ago I noticed a significant drop in FPS. Is this an issue for anyone else or is it local?

**Comment by msmalik681** [comment]
Best to ask in the discord

**Comment by VeteranSquared** [comment]
Alright. Could it have been due to an update of sort?

**Comment by VeteranSquared** [comment]
It's fixed now. I don't know what happened but it's all good
