### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by debian-user-france1** [msmalik681/Maliks-Linux-Roblox-Wrapper#2]
still same behaviour. You can't simply run roblox on wine

**Comment by msmalik681** [comment]
Join the discord for support https://discord.gg/xxTqHaGU

**Comment by debian-user-france1** [comment]
I maybe don't have Discord or just don't want to join your server lol

I've just another source where I can install Roblox lol
This Script will not work nowadays

Just reported there that I've a problem with their stuff but basically it works (but just not currently for me)
