### ISSUE TITLE
pop os white screen

### ISSUE THREAD

**Issue by XX00115** [msmalik681/Maliks-Linux-Roblox-Wrapper#21]
pls help whenever i launch roblox on pop os screen is white i cant fix it pls help

**Comment by msmalik681** [comment]
maybe try updating your graphics drivers.

AMD/INTEL: sudo add-apt-repository ppa:kisak/kisak-mesa && sudo dpkg --add-architecture i386 && sudo apt update && sudo apt upgrade && sudo apt install libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386

NVIDIA: sudo add-apt-repository ppa:graphics-drivers/ppa && sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install -y nvidia-driver-515 libvulkan1 libvulkan1:i386

WARNING: if your using nvidia make sure your gpu supports the 515 drivers you can find a list here: https://www.nvidia.com/Download/driverResults.aspx/186156/en-us/

**Comment by XX00115** [comment]
thank you bro you are a lifesaver

**Comment by XX00115** [comment]
it keeps crashing tho, do you know how to fix that?

**Comment by msmalik681** [comment]
This was fixed
