### ISSUE TITLE
White screen when launching game

### ISSUE THREAD

**Issue by Redgamer6** [msmalik681/Maliks-Linux-Roblox-Wrapper#4]
Occasionally when launching a Roblox game Roblox will launch but will stay permanently on a white screen, sometimes exiting and rejoining will fix it but other times a full system restart is required to fix it. While I can work around the issue for the time being it would be great if this issue could be fixed in the next update. I am using Pop!_OS 21.04

**Comment by msmalik681** [comment]
I am also on Pop! OS but 20.04 does this happen with all API's and what GPU are you using ?

**Comment by Redgamer6** [comment]
alright so i think i figured out what is causing it. It seems to only happen when I close the wine system tray. I thought I could close it to get it out of the way but apparently not, if there is a way to run the system tray in the background that would be nice but not necessary. You can close this issue if you like now.

**Comment by msmalik681** [comment]
Thanks closing now.

**Comment by konstantinepapakonstantinou** [comment]
I'm also running Pop!_OS 21.04 and running into this issue. @Redgamer6 how do you go about keeping the system tray open?

**Comment by triface123022** [comment]
For me i am on Ubuntu 22.10 and it shows a white screen but roblox opens and i only hear the sound

**Comment by PiesekChlebek** [comment]
> For me i am on Ubuntu 22.10 and it shows a white screen but roblox opens and i only hear the sound

me to
