### ISSUE TITLE
FPS Unlocker dosen't work and being fullscreen on Vulkan freezes your game 

### ISSUE THREAD

**Issue by thatshadycodeboi** [msmalik681/Maliks-Linux-Roblox-Wrapper#7]
1. GTX 970 Zotac
2. I5 3470 
3. 8 gb DDR3
4. Pop_OS! 21.04

All options (Vulkan, OpenGL, DX9 and DX11) freeze your instance when trying to fullscreen (although DX11 works somewhat after trying to spam F11, it's still not convenient) and FPS Unlocker doesn't work outright

**Comment by msmalik681** [comment]
I am aware of this issue and trying to reproduce without luck can you give further insight on your setup?

Your desktop enviroment

Desktop resolution 

Your system version of wine

**Comment by thatshadycodeboi** [comment]
Oh sorry for being late - GNOME 3.38 i think (with Dash To Panel)
                                     - 1920x1200
                                     - wine-tkg 6.16 staging
                                     - and NVIDIA 470 driver version proprietary

**Comment by thatshadycodeboi** [comment]
And RBLX FPS Unlocker works now, it doesn't open in my dash to pane extension

**Comment by morschu** [comment]
I have the same issue too, the unlocker works tho, when i go in fullscreen it works for 2-3 seconds and then freezes
My specs are--
1920x1080
GTX 1650 Mobile(Version 470 propietary)
Pop_Os 21.04
Wine 6.0

**Comment by msmalik681** [comment]
@thatshadycodeboi and @morschu can you test [release 5.0](https://github.com/msmalik681/Maliks-Linux-Roblox-Wrapper/releases/tag/v5.0) and confirm if your still having issues with full screen and fps unlocker ?

**Comment by msmalik681** [comment]
Native fps unlocker now supported
