### ISSUE TITLE
Roblox Studio doesnt launch.

### ISSUE THREAD

**Issue by morschu** [msmalik681/Maliks-Linux-Roblox-Wrapper#8]
It doesnt launch, when i click on it.
My specs are given below:-
GTX 1650(Mobile; Driver version 470)
1920x1080
Ryzen 5 4600H
8gb DDR4
Pop_Os 21.04
Wine 6.0.2

**Comment by msmalik681** [comment]
You should be launching from the website

**Comment by morschu** [comment]
Thanks :)

**Comment by morschu** [comment]
It still doesnt open

**Comment by morschu** [comment]
maybe ill just install grapejuice and use roblox studio from there?

**Comment by msmalik681** [comment]
Does roblox player work with vulkan api ?

**Comment by TouseefX** [comment]
the porblem is u using old wine the roblox studuo need winehq 6.1.0 but the wrapper keep downloaing the other one so u need to chage script to foreced to download the wine 6.1.0

**Comment by brotherman123** [comment]
It stops giving me the error window but keeps loading for years on end i am only using malik for roblox studio rest is with vinegar.

**Comment by msmalik681** [comment]
current release is confirmed working so im closing this down
